# Generated by Django 5.0.14 on 2025-05-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_produto_registromovimentacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default='Geral', max_length=100),
        ),
    ]
